# -*- coding: utf-8 -*-
"""BTVN_TUAN 2_2.13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_xvB2EGBGh0Hn9E-m7p9N2Aqe0aPfDl
"""

!pip install scikit-fuzzy ipywidgets

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import ipywidgets as widgets
from IPython.display import display, clear_output

# ===================== BIẾN FUZZY =====================

nhu_cau_san_pham = ctrl.Antecedent(np.arange(0, 101, 1), 'nhu_cau_san_pham')
ap_luc_canh_tranh = ctrl.Antecedent(np.arange(0, 101, 1), 'ap_luc_canh_tranh')
uy_tin_cua_hang = ctrl.Antecedent(np.arange(1, 5.1, 0.1), 'uy_tin_cua_hang')
bien_loi_nhuan = ctrl.Antecedent(np.arange(0, 71, 1), 'bien_loi_nhuan')
nhu_cau_theo_mua = ctrl.Antecedent(np.arange(0, 101, 1), 'nhu_cau_theo_mua')

chiet_khau = ctrl.Consequent(np.arange(0, 71, 1), 'chiet_khau')

# ===================== TẬP MỜ INPUT =====================

nhu_cau_san_pham['thap'] = fuzz.trimf(nhu_cau_san_pham.universe, [0, 0, 40])
nhu_cau_san_pham['trung_binh'] = fuzz.trimf(nhu_cau_san_pham.universe, [30, 50, 70])
nhu_cau_san_pham['cao'] = fuzz.trimf(nhu_cau_san_pham.universe, [60, 100, 100])

ap_luc_canh_tranh['thap'] = fuzz.trimf(ap_luc_canh_tranh.universe, [0, 0, 40])
ap_luc_canh_tranh['trung_binh'] = fuzz.trimf(ap_luc_canh_tranh.universe, [30, 50, 70])
ap_luc_canh_tranh['cao'] = fuzz.trimf(ap_luc_canh_tranh.universe, [60, 100, 100])

uy_tin_cua_hang['thap'] = fuzz.trimf(uy_tin_cua_hang.universe, [1.0, 1.0, 4.0])
uy_tin_cua_hang['trung_binh'] = fuzz.trimf(uy_tin_cua_hang.universe, [4.0, 4.25, 4.5])
uy_tin_cua_hang['cao'] = fuzz.trimf(uy_tin_cua_hang.universe, [4.5, 5.0, 5.0])

bien_loi_nhuan['thap'] = fuzz.trimf(bien_loi_nhuan.universe, [0, 0, 20])
bien_loi_nhuan['trung_binh'] = fuzz.trimf(bien_loi_nhuan.universe, [15, 30, 45])
bien_loi_nhuan['cao'] = fuzz.trimf(bien_loi_nhuan.universe, [40, 70, 70])

nhu_cau_theo_mua['khong_co'] = fuzz.trimf(nhu_cau_theo_mua.universe, [0, 0, 30])
nhu_cau_theo_mua['trung_binh'] = fuzz.trimf(nhu_cau_theo_mua.universe, [20, 50, 70])
nhu_cau_theo_mua['cao'] = fuzz.trimf(nhu_cau_theo_mua.universe, [60, 100, 100])

# ===================== TẬP MỜ OUTPUT =====================

chiet_khau['rat_thap'] = fuzz.trimf(chiet_khau.universe, [0, 0, 5])
chiet_khau['thap'] = fuzz.trimf(chiet_khau.universe, [5, 7.5, 10])
chiet_khau['trung_binh'] = fuzz.trimf(chiet_khau.universe, [10, 17.5, 25])
chiet_khau['cao'] = fuzz.trimf(chiet_khau.universe, [20, 30, 40])
chiet_khau['rat_cao'] = fuzz.trimf(chiet_khau.universe, [40, 70, 70])

# ===================== 7 LUẬT MỜ THEO ĐỀ 2.13 =====================

luat = [
    ctrl.Rule(
        nhu_cau_san_pham['cao'] &
        ap_luc_canh_tranh['thap'] &
        bien_loi_nhuan['cao'],
        chiet_khau['rat_thap']
    ),

    ctrl.Rule(
        nhu_cau_san_pham['thap'] &
        ap_luc_canh_tranh['cao'] &
        bien_loi_nhuan['cao'],
        chiet_khau['cao']
    ),

    ctrl.Rule(
        uy_tin_cua_hang['cao'] &
        bien_loi_nhuan['trung_binh'] &
        nhu_cau_theo_mua['cao'],
        chiet_khau['trung_binh']
    ),

    ctrl.Rule(
        ap_luc_canh_tranh['cao'] &
        nhu_cau_theo_mua['cao'] &
        bien_loi_nhuan['cao'],
        chiet_khau['rat_cao']
    ),

    ctrl.Rule(
        uy_tin_cua_hang['thap'] &
        nhu_cau_san_pham['trung_binh'] &
        bien_loi_nhuan['thap'],
        chiet_khau['trung_binh']
    ),

    ctrl.Rule(
        nhu_cau_san_pham['cao'] &
        nhu_cau_theo_mua['khong_co'] &
        ap_luc_canh_tranh['thap'],
        chiet_khau['rat_thap']
    ),

    ctrl.Rule(
        bien_loi_nhuan['cao'] &
        ap_luc_canh_tranh['trung_binh'] &
        nhu_cau_theo_mua['trung_binh'],
        chiet_khau['trung_binh']
    ),

    ctrl.Rule(
        nhu_cau_san_pham['trung_binh'] |
        ap_luc_canh_tranh['trung_binh'] |
        nhu_cau_theo_mua['trung_binh'],
        chiet_khau['trung_binh']
    )
]

he_thong_ctrl = ctrl.ControlSystem(luat)

# ===================== HÀM PHỤ =====================

def phan_loai_chiet_khau(phan_tram):
    if phan_tram < 5:
        return "Rất thấp"
    elif phan_tram < 10:
        return "Thấp"
    elif phan_tram < 25:
        return "Trung bình"
    elif phan_tram < 40:
        return "Cao"
    else:
        return "Rất cao"

def tinh_loi_nhuan(gia_ban, gia_von, phan_tram_giam):
    gia_sau_giam = gia_ban * (1 - phan_tram_giam / 100)
    loi_nhuan = gia_sau_giam - gia_von
    ty_suat = (loi_nhuan / gia_sau_giam) * 100 if gia_sau_giam > 0 else 0
    return gia_sau_giam, loi_nhuan, ty_suat

def goi_y_chien_luoc(muc_chiet_khau, loi_nhuan):
    if loi_nhuan < 0:
        return "Cảnh báo: mức giảm này có thể gây lỗ, nên giảm nhẹ hoặc bán theo combo."
    elif muc_chiet_khau in ["Rất thấp", "Thấp"]:
        return "Sản phẩm có lợi thế, không cần giảm mạnh. Nên tập trung vào chất lượng và hình ảnh."
    elif muc_chiet_khau == "Trung bình":
        return "Có thể áp dụng voucher vừa phải để kích thích mua nhưng vẫn giữ lợi nhuận."
    elif muc_chiet_khau == "Cao":
        return "Nên dùng trong thời gian ngắn để tăng đơn hàng và cạnh tranh."
    else:
        return "Chỉ nên dùng khi có sự kiện lớn hoặc áp lực cạnh tranh rất mạnh."

# ===================== UI =====================

o_san_pham = widgets.Text(
    value="Đồng hồ xa xỉ thủ công",
    description="Sản phẩm:",
    layout=widgets.Layout(width="600px")
)

o_gia_ban = widgets.IntText(
    value=1000000,
    description="Giá bán:"
)

o_gia_von = widgets.IntText(
    value=650000,
    description="Giá vốn:"
)

slider_nhu_cau = widgets.IntSlider(
    value=80,
    min=0,
    max=100,
    step=1,
    description="Nhu cầu SP:",
    layout=widgets.Layout(width="600px")
)

slider_canh_tranh = widgets.IntSlider(
    value=50,
    min=0,
    max=100,
    step=1,
    description="Cạnh tranh:",
    layout=widgets.Layout(width="600px")
)

slider_uy_tin = widgets.FloatSlider(
    value=4.2,
    min=1.0,
    max=5.0,
    step=0.1,
    description="Uy tín shop:",
    layout=widgets.Layout(width="600px")
)

slider_loi_nhuan = widgets.IntSlider(
    value=60,
    min=0,
    max=70,
    step=1,
    description="Biên LN:",
    layout=widgets.Layout(width="600px")
)

slider_theo_mua = widgets.IntSlider(
    value=80,
    min=0,
    max=100,
    step=1,
    description="Nhu cầu mùa:",
    layout=widgets.Layout(width="600px")
)

nut_tinh = widgets.Button(
    description="Tính chiến lược giảm giá",
    button_style="success"
)

output = widgets.Output()

def xu_ly_tinh(b):
    with output:
        clear_output()

        he_thong = ctrl.ControlSystemSimulation(he_thong_ctrl)

        he_thong.input['nhu_cau_san_pham'] = slider_nhu_cau.value
        he_thong.input['ap_luc_canh_tranh'] = slider_canh_tranh.value
        he_thong.input['uy_tin_cua_hang'] = slider_uy_tin.value
        he_thong.input['bien_loi_nhuan'] = slider_loi_nhuan.value
        he_thong.input['nhu_cau_theo_mua'] = slider_theo_mua.value

        he_thong.compute()

        phan_tram = he_thong.output.get('chiet_khau', 15)
        muc = phan_loai_chiet_khau(phan_tram)

        gia_sau_giam, loi_nhuan, ty_suat = tinh_loi_nhuan(
            o_gia_ban.value,
            o_gia_von.value,
            phan_tram
        )

        print("KẾT QUẢ KẾ HOẠCH CHIẾN LƯỢC BÁN HÀNG SHOPEE")
        print("------------------------------------------------")
        print("Sản phẩm:", o_san_pham.value)
        print("Giá bán gốc:", f"{o_gia_ban.value:,.0f}", "VNĐ")
        print("Giá vốn:", f"{o_gia_von.value:,.0f}", "VNĐ")
        print("Nhu cầu sản phẩm:", slider_nhu_cau.value, "/ 100")
        print("Áp lực cạnh tranh:", slider_canh_tranh.value, "/ 100")
        print("Uy tín cửa hàng:", slider_uy_tin.value, "/ 5")
        print("Biên lợi nhuận:", slider_loi_nhuan.value, "%")
        print("Nhu cầu theo mùa:", slider_theo_mua.value, "/ 100")
        print("------------------------------------------------")
        print("Chiết khấu đề xuất:", round(phan_tram, 2), "%")
        print("Mức chiết khấu:", muc)
        print("Giá sau giảm:", f"{gia_sau_giam:,.0f}", "VNĐ")
        print("Lợi nhuận sau giảm:", f"{loi_nhuan:,.0f}", "VNĐ")
        print("Tỷ suất lợi nhuận sau giảm:", round(ty_suat, 2), "%")
        print("------------------------------------------------")
        print("Gợi ý chiến lược:", goi_y_chien_luoc(muc, loi_nhuan))
        print("------------------------------------------------")
        print("GIẢI THÍCH:")

        if slider_nhu_cau.value >= 60:
            print("- Nhu cầu sản phẩm cao nên không nhất thiết phải giảm giá quá mạnh.")
        else:
            print("- Nhu cầu sản phẩm chưa cao nên cần dùng giảm giá để kích thích mua.")

        if slider_canh_tranh.value >= 60:
            print("- Áp lực cạnh tranh cao nên cửa hàng cần tăng ưu đãi để giữ khách.")
        elif slider_canh_tranh.value <= 40:
            print("- Áp lực cạnh tranh thấp nên có thể giữ giá để bảo toàn lợi nhuận.")

        if slider_uy_tin.value >= 4.5:
            print("- Uy tín cửa hàng cao giúp sản phẩm dễ bán hơn, giảm giá có thể thấp hơn.")
        elif slider_uy_tin.value < 4.0:
            print("- Uy tín cửa hàng thấp nên cần ưu đãi để thu hút khách hàng ban đầu.")

        if slider_loi_nhuan.value >= 40:
            print("- Biên lợi nhuận cao cho phép linh hoạt giảm giá nếu cần.")
        else:
            print("- Biên lợi nhuận thấp nên cần cẩn thận để tránh bán lỗ.")

        if slider_theo_mua.value >= 60:
            print("- Nhu cầu theo mùa cao, có thể tận dụng chiến dịch sale để tăng doanh thu.")
        else:
            print("- Không có mùa cao điểm, nên tránh giảm giá quá sâu.")

nut_tinh.on_click(xu_ly_tinh)

display(widgets.HTML("<h2>HỆ THỐNG KẾ HOẠCH CHIẾN LƯỢC BÁN HÀNG SHOPEE BẰNG FUZZY LOGIC</h2>"))
display(widgets.HTML("<b>Thông tin sản phẩm</b>"))
display(o_san_pham, o_gia_ban, o_gia_von)

display(widgets.HTML("<b>Các yếu tố ảnh hưởng đến chiến lược giảm giá</b>"))
display(slider_nhu_cau)
display(slider_canh_tranh)
display(slider_uy_tin)
display(slider_loi_nhuan)
display(slider_theo_mua)

display(nut_tinh)
display(output)