# -*- coding: utf-8 -*-
"""BTVN_TUAN 2_2.14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12boQH6mBMdOYME9d1WJ3I0Rvfm695OR9
"""

!pip install scikit-fuzzy ipywidgets

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import ipywidgets as widgets
from IPython.display import display, clear_output

# =========================
# BIẾN INPUT
# =========================

mat_do_don = ctrl.Antecedent(np.arange(0,101,1),'mat_do_don')
khan_cap = ctrl.Antecedent(np.arange(0,101,1),'khan_cap')
tai_trong = ctrl.Antecedent(np.arange(0,101,1),'tai_trong')
giao_thong = ctrl.Antecedent(np.arange(0,101,1),'giao_thong')
loi_nhuan = ctrl.Antecedent(np.arange(0,101,1),'loi_nhuan')

# OUTPUT
so_don_ghep = ctrl.Consequent(np.arange(0,11,1),'so_don_ghep')
uu_tien = ctrl.Consequent(np.arange(0,101,1),'uu_tien')

# =========================
# FUZZY SET
# =========================

def tao_3_muc(var):
    var['thap'] = fuzz.trimf(var.universe,[0,0,40])
    var['trung_binh'] = fuzz.trimf(var.universe,[30,50,70])
    var['cao'] = fuzz.trimf(var.universe,[60,100,100])

for v in [mat_do_don,khan_cap,tai_trong,giao_thong,loi_nhuan]:
    tao_3_muc(v)

so_don_ghep['it'] = fuzz.trimf(so_don_ghep.universe,[0,1,3])
so_don_ghep['mot_vai'] = fuzz.trimf(so_don_ghep.universe,[2,4,6])
so_don_ghep['nhieu'] = fuzz.trimf(so_don_ghep.universe,[5,10,10])

uu_tien['thap'] = fuzz.trimf(uu_tien.universe,[0,0,40])
uu_tien['trung_binh'] = fuzz.trimf(uu_tien.universe,[30,50,70])
uu_tien['cao'] = fuzz.trimf(uu_tien.universe,[60,100,100])

# =========================
# LUẬT MỜ (ĐÚNG ĐỀ)
# =========================

rules = [

# --- GỘP ĐƠN ---

ctrl.Rule(mat_do_don['cao'] & tai_trong['thap'] & giao_thong['thap'], so_don_ghep['nhieu']),

ctrl.Rule(mat_do_don['trung_binh'] & giao_thong['cao'] & khan_cap['trung_binh'], so_don_ghep['mot_vai']),

ctrl.Rule(tai_trong['cao'] & mat_do_don['cao'] & loi_nhuan['trung_binh'], so_don_ghep['mot_vai']),

ctrl.Rule(mat_do_don['thap'] & khan_cap['cao'] & giao_thong['trung_binh'], so_don_ghep['mot_vai']),

ctrl.Rule(loi_nhuan['cao'] & khan_cap['cao'] & giao_thong['cao'], so_don_ghep['mot_vai']),


# --- ƯU TIÊN GIAO ---

ctrl.Rule(khan_cap['cao'] & loi_nhuan['cao'], uu_tien['cao']),

ctrl.Rule(khan_cap['trung_binh'] & giao_thong['trung_binh'], uu_tien['trung_binh']),

ctrl.Rule(khan_cap['thap'] & mat_do_don['cao'] & loi_nhuan['thap'], uu_tien['thap'])
]

system = ctrl.ControlSystem(rules)

# =========================
# HÀM PHÂN LOẠI
# =========================

def label_don(x):
    if x < 3: return "Ít đơn"
    elif x < 6: return "Một vài đơn"
    else: return "Nhiều đơn"

def label_uu_tien(x):
    if x < 40: return "Ưu tiên thấp (giao sau)"
    elif x < 70: return "Ưu tiên trung bình"
    else: return "Ưu tiên cao (giao trước)"

# =========================
# UI
# =========================

s_md = widgets.IntSlider(value=80,min=0,max=100,description='Mật độ đơn')
s_kc = widgets.IntSlider(value=50,min=0,max=100,description='Khẩn cấp')
s_tt = widgets.IntSlider(value=30,min=0,max=100,description='Tải tài xế')
s_gt = widgets.IntSlider(value=50,min=0,max=100,description='Giao thông')
s_ln = widgets.IntSlider(value=50,min=0,max=100,description='Lợi nhuận')

btn = widgets.Button(description="Tối ưu giao hàng",button_style='success')
out = widgets.Output()

# =========================
# XỬ LÝ
# =========================

def run(b):
    with out:
        clear_output()

        sim = ctrl.ControlSystemSimulation(system)

        sim.input['mat_do_don'] = s_md.value
        sim.input['khan_cap'] = s_kc.value
        sim.input['tai_trong'] = s_tt.value
        sim.input['giao_thong'] = s_gt.value
        sim.input['loi_nhuan'] = s_ln.value

        sim.compute()

        don = sim.output.get('so_don_ghep',3)
        ut = sim.output.get('uu_tien',50)

        print("===== KẾT QUẢ TỐI ƯU =====")
        print("Số đơn nên ghép:", round(don,1),"→",label_don(don))
        print("Mức ưu tiên:", round(ut,1),"→",label_uu_tien(ut))

        print("\n===== GIẢI THÍCH =====")

        if s_md.value > 60:
            print("- Mật độ đơn cao → nên ghép nhiều đơn để tối ưu.")
        else:
            print("- Mật độ đơn thấp → không cần ghép nhiều.")

        if s_tt.value < 40:
            print("- Tài xế đang rảnh → có thể nhận thêm đơn.")
        else:
            print("- Tài xế gần full tải → hạn chế ghép.")

        if s_kc.value > 60:
            print("- Đơn khẩn cấp → ưu tiên giao trước.")

        if s_gt.value > 60:
            print("- Giao thông kẹt → giảm số đơn ghép để tránh trễ.")

        if s_ln.value > 60:
            print("- Đơn lợi nhuận cao → ưu tiên xử lý trước.")

btn.on_click(run)

# =========================
# HIỂN THỊ
# =========================

display(widgets.HTML("<h2>TỐI ƯU GIAO HÀNG (BÀI 2.14)</h2>"))
display(s_md,s_kc,s_tt,s_gt,s_ln,btn,out)