# -*- coding: utf-8 -*-
"""BTVN_TUAN 2_2.12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJMuV2J0hmZOUgsMf8xb5jmaeUhsGVsz
"""

!pip install scikit-fuzzy ipywidgets

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import ipywidgets as widgets
from IPython.display import display, clear_output

# ===================== BIẾN FUZZY =====================

xep_hang = ctrl.Antecedent(np.arange(1, 5.1, 0.1), 'xep_hang')
khoi_luong_ban = ctrl.Antecedent(np.arange(0, 101, 1), 'khoi_luong_ban')
bien_loi_nhuan = ctrl.Antecedent(np.arange(0, 71, 1), 'bien_loi_nhuan')
su_kien_mua = ctrl.Antecedent(np.arange(0, 101, 1), 'su_kien_mua')
giam_gia_doi_thu = ctrl.Antecedent(np.arange(0, 71, 1), 'giam_gia_doi_thu')

chiet_khau = ctrl.Consequent(np.arange(0, 71, 1), 'chiet_khau')

# ===================== TẬP MỜ INPUT =====================

xep_hang['thap'] = fuzz.trimf(xep_hang.universe, [1, 1, 4.0])
xep_hang['trung_binh'] = fuzz.trimf(xep_hang.universe, [4.0, 4.25, 4.5])
xep_hang['cao'] = fuzz.trimf(xep_hang.universe, [4.5, 5.0, 5.0])

khoi_luong_ban['thap'] = fuzz.trimf(khoi_luong_ban.universe, [0, 0, 40])
khoi_luong_ban['trung_binh'] = fuzz.trimf(khoi_luong_ban.universe, [30, 50, 70])
khoi_luong_ban['cao'] = fuzz.trimf(khoi_luong_ban.universe, [60, 100, 100])

bien_loi_nhuan['thap'] = fuzz.trimf(bien_loi_nhuan.universe, [0, 0, 20])
bien_loi_nhuan['trung_binh'] = fuzz.trimf(bien_loi_nhuan.universe, [15, 30, 45])
bien_loi_nhuan['cao'] = fuzz.trimf(bien_loi_nhuan.universe, [40, 70, 70])

su_kien_mua['khong_co'] = fuzz.trimf(su_kien_mua.universe, [0, 0, 30])
su_kien_mua['trung_binh'] = fuzz.trimf(su_kien_mua.universe, [20, 50, 70])
su_kien_mua['cao'] = fuzz.trimf(su_kien_mua.universe, [60, 100, 100])

giam_gia_doi_thu['thap'] = fuzz.trimf(giam_gia_doi_thu.universe, [0, 0, 10])
giam_gia_doi_thu['trung_binh'] = fuzz.trimf(giam_gia_doi_thu.universe, [5, 20, 35])
giam_gia_doi_thu['cao'] = fuzz.trimf(giam_gia_doi_thu.universe, [30, 70, 70])

# ===================== TẬP MỜ OUTPUT =====================

chiet_khau['rat_thap'] = fuzz.trimf(chiet_khau.universe, [0, 0, 5])
chiet_khau['thap'] = fuzz.trimf(chiet_khau.universe, [5, 7.5, 10])
chiet_khau['trung_binh'] = fuzz.trimf(chiet_khau.universe, [10, 15, 20])
chiet_khau['cao'] = fuzz.trimf(chiet_khau.universe, [20, 30, 40])
chiet_khau['rat_cao'] = fuzz.trimf(chiet_khau.universe, [40, 70, 70])

# ===================== 7 LUẬT MỜ THEO ĐỀ =====================

luat = [
    ctrl.Rule(xep_hang['cao'] & khoi_luong_ban['cao'] & bien_loi_nhuan['cao'], chiet_khau['rat_thap']),

    ctrl.Rule(xep_hang['thap'] & khoi_luong_ban['thap'] & bien_loi_nhuan['cao'], chiet_khau['cao']),

    ctrl.Rule(su_kien_mua['cao'] & giam_gia_doi_thu['cao'], chiet_khau['rat_cao']),

    ctrl.Rule(xep_hang['trung_binh'] & khoi_luong_ban['trung_binh'] & bien_loi_nhuan['trung_binh'], chiet_khau['trung_binh']),

    ctrl.Rule(giam_gia_doi_thu['thap'] & bien_loi_nhuan['thap'] & khoi_luong_ban['cao'], chiet_khau['rat_thap']),

    ctrl.Rule(xep_hang['thap'] & su_kien_mua['khong_co'], chiet_khau['trung_binh']),

    ctrl.Rule(khoi_luong_ban['thap'] & bien_loi_nhuan['thap'], chiet_khau['rat_cao']),

    ctrl.Rule(su_kien_mua['trung_binh'] | giam_gia_doi_thu['trung_binh'] | xep_hang['trung_binh'], chiet_khau['trung_binh'])
]

he_thong_ctrl = ctrl.ControlSystem(luat)

# ===================== HÀM PHÂN LOẠI =====================

def phan_loai_chiet_khau(phan_tram):
    if phan_tram < 5:
        return "Rất thấp"
    elif phan_tram < 10:
        return "Thấp"
    elif phan_tram < 20:
        return "Trung bình"
    elif phan_tram < 40:
        return "Cao"
    else:
        return "Rất cao"

def tinh_loi_nhuan(gia_ban, gia_von, phan_tram_giam):
    gia_sau_giam = gia_ban * (1 - phan_tram_giam / 100)
    loi_nhuan = gia_sau_giam - gia_von
    ty_suat_loi_nhuan = (loi_nhuan / gia_sau_giam) * 100 if gia_sau_giam > 0 else 0
    return gia_sau_giam, loi_nhuan, ty_suat_loi_nhuan

def goi_y_chien_luoc(muc_chiet_khau, loi_nhuan):
    if loi_nhuan < 0:
        return "Cảnh báo: mức giảm này có thể gây lỗ, nên giảm nhẹ hơn hoặc bán theo combo."
    if muc_chiet_khau in ["Rất cao", "Cao"]:
        return "Nên áp dụng trong thời gian ngắn, ví dụ flash sale hoặc sự kiện lớn."
    if muc_chiet_khau == "Trung bình":
        return "Có thể áp dụng voucher hoặc mã giảm giá vừa phải để kích thích mua hàng."
    return "Không cần giảm mạnh, nên tập trung giữ lợi nhuận và chất lượng dịch vụ."

# ===================== UI =====================

o_gia_ban = widgets.IntText(value=100000, description="Giá bán:")
o_gia_von = widgets.IntText(value=70000, description="Giá vốn:")

slider_xep_hang = widgets.FloatSlider(
    value=4.3, min=1.0, max=5.0, step=0.1,
    description="Xếp hạng:", layout=widgets.Layout(width="550px")
)

slider_khoi_luong = widgets.IntSlider(
    value=50, min=0, max=100, step=1,
    description="Bán hàng:", layout=widgets.Layout(width="550px")
)

slider_loi_nhuan = widgets.IntSlider(
    value=20, min=0, max=70, step=1,
    description="Biên LN:", layout=widgets.Layout(width="550px")
)

slider_su_kien = widgets.IntSlider(
    value=80, min=0, max=100, step=1,
    description="Sự kiện:", layout=widgets.Layout(width="550px")
)

slider_doi_thu = widgets.IntSlider(
    value=50, min=0, max=70, step=1,
    description="Đối thủ:", layout=widgets.Layout(width="550px")
)

nut_tinh = widgets.Button(description="Tính chiết khấu", button_style="success")
output = widgets.Output()

def xu_ly_tinh(b):
    with output:
        clear_output()

        he_thong = ctrl.ControlSystemSimulation(he_thong_ctrl)

        he_thong.input['xep_hang'] = slider_xep_hang.value
        he_thong.input['khoi_luong_ban'] = slider_khoi_luong.value
        he_thong.input['bien_loi_nhuan'] = slider_loi_nhuan.value
        he_thong.input['su_kien_mua'] = slider_su_kien.value
        he_thong.input['giam_gia_doi_thu'] = slider_doi_thu.value

        he_thong.compute()

        phan_tram = he_thong.output.get('chiet_khau', 15)
        muc = phan_loai_chiet_khau(phan_tram)

        gia_sau_giam, loi_nhuan, ty_suat = tinh_loi_nhuan(
            o_gia_ban.value,
            o_gia_von.value,
            phan_tram
        )

        print("KẾT QUẢ CHIẾN LƯỢC CHIẾT KHẤU SHOPEE")
        print("--------------------------------------")
        print("Giá bán gốc:", f"{o_gia_ban.value:,.0f}", "VNĐ")
        print("Giá vốn:", f"{o_gia_von.value:,.0f}", "VNĐ")
        print("Xếp hạng cửa hàng:", slider_xep_hang.value, "/ 5")
        print("Khối lượng bán:", slider_khoi_luong.value, "/ 100")
        print("Biên lợi nhuận:", slider_loi_nhuan.value, "%")
        print("Sự kiện theo mùa:", slider_su_kien.value, "/ 100")
        print("Giảm giá đối thủ:", slider_doi_thu.value, "%")
        print("--------------------------------------")
        print("Chiết khấu đề xuất:", round(phan_tram, 2), "%")
        print("Mức chiết khấu:", muc)
        print("Giá sau giảm:", f"{gia_sau_giam:,.0f}", "VNĐ")
        print("Lợi nhuận sau giảm:", f"{loi_nhuan:,.0f}", "VNĐ")
        print("Tỷ suất lợi nhuận sau giảm:", round(ty_suat, 2), "%")
        print("--------------------------------------")
        print("Gợi ý:", goi_y_chien_luoc(muc, loi_nhuan))

        print("--------------------------------------")
        print("GIẢI THÍCH:")
        if slider_su_kien.value >= 60:
            print("- Đang có sự kiện mua sắm lớn nên có xu hướng tăng chiết khấu.")
        if slider_doi_thu.value >= 30:
            print("- Đối thủ đang giảm giá mạnh nên cửa hàng cần tăng tính cạnh tranh.")
        if slider_loi_nhuan.value <= 20:
            print("- Biên lợi nhuận thấp nên cần cẩn thận để tránh giảm giá quá mức.")
        if slider_xep_hang.value >= 4.5:
            print("- Cửa hàng có xếp hạng cao nên không nhất thiết phải giảm giá mạnh.")
        if slider_khoi_luong.value <= 40:
            print("- Khối lượng bán thấp nên có thể cần chiết khấu để kích thích doanh số.")

nut_tinh.on_click(xu_ly_tinh)

display(widgets.HTML("<h2>HỆ THỐNG GỢI Ý CHIẾT KHẤU SHOPEE BẰNG FUZZY LOGIC</h2>"))
display(widgets.HTML("<b>Thông tin sản phẩm</b>"))
display(o_gia_ban, o_gia_von)

display(widgets.HTML("<b>Yếu tố ảnh hưởng đến quyết định giảm giá</b>"))
display(slider_xep_hang)
display(slider_khoi_luong)
display(slider_loi_nhuan)
display(slider_su_kien)
display(slider_doi_thu)

display(nut_tinh)
display(output)