# -*- coding: utf-8 -*-
"""BTVN_TUAN 2_2.11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixE3ndMf5GfmikdpvxyyzVI6Sy5cAn-8
"""

# ===================== CÀI THƯ VIỆN =====================
!pip install scikit-fuzzy folium ipywidgets

# ===================== IMPORT =====================
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import folium
import ipywidgets as widgets
from IPython.display import display, clear_output
from math import radians, sin, cos, sqrt, atan2

# ===================== DATA ĐỊA ĐIỂM =====================
dia_diem = {
    "UEH Nguyễn Văn Linh": (10.7298, 106.7216),
    "UEH Nguyễn Tri Phương": (10.7634, 106.6663),
    "Chợ Bến Thành": (10.7725, 106.6980),
    "Landmark 81": (10.7950, 106.7218),
    "Sân bay Tân Sơn Nhất": (10.8189, 106.6519),
    "Nhà thờ Đức Bà": (10.7798, 106.6990),
    "Dinh Độc Lập": (10.7770, 106.6954),
    "Bitexco": (10.7717, 106.7044)
}

# ===================== FUZZY =====================
khoang_cach = ctrl.Antecedent(np.arange(0, 51, 1), 'khoang_cach')
giao_thong = ctrl.Antecedent(np.arange(0, 101, 1), 'giao_thong')
nhu_cau = ctrl.Antecedent(np.arange(0, 101, 1), 'nhu_cau')
thoi_tiet = ctrl.Antecedent(np.arange(0, 101, 1), 'thoi_tiet')
danh_gia = ctrl.Antecedent(np.arange(1, 5.1, 0.1), 'danh_gia')
dung_gio = ctrl.Antecedent(np.arange(0, 101, 1), 'dung_gio')

he_so_gia = ctrl.Consequent(np.arange(1.0, 3.1, 0.1), 'he_so_gia')
diem_thuong = ctrl.Consequent(np.arange(0, 101, 1), 'diem_thuong')

# membership
khoang_cach['ngan'] = fuzz.trimf(khoang_cach.universe, [0, 0, 3])
khoang_cach['trung_binh'] = fuzz.trimf(khoang_cach.universe, [2, 5, 8])
khoang_cach['dai'] = fuzz.trimf(khoang_cach.universe, [6, 13, 20])
khoang_cach['rat_xa'] = fuzz.trimf(khoang_cach.universe, [15, 50, 50])

giao_thong['thap'] = fuzz.trimf(giao_thong.universe, [0, 0, 30])
giao_thong['trung_binh'] = fuzz.trimf(giao_thong.universe, [20, 50, 70])
giao_thong['cao'] = fuzz.trimf(giao_thong.universe, [60, 100, 100])

nhu_cau['thap'] = fuzz.trimf(nhu_cau.universe, [0, 0, 30])
nhu_cau['trung_binh'] = fuzz.trimf(nhu_cau.universe, [20, 50, 70])
nhu_cau['cao'] = fuzz.trimf(nhu_cau.universe, [60, 100, 100])

thoi_tiet['tot'] = fuzz.trimf(thoi_tiet.universe, [0, 0, 30])
thoi_tiet['trung_binh'] = fuzz.trimf(thoi_tiet.universe, [20, 50, 70])
thoi_tiet['xau'] = fuzz.trimf(thoi_tiet.universe, [60, 100, 100])

danh_gia['kem'] = fuzz.trimf(danh_gia.universe, [1.0, 1.0, 2.5])
danh_gia['trung_binh'] = fuzz.trimf(danh_gia.universe, [2.0, 3.0, 4.0])
danh_gia['tot'] = fuzz.trimf(danh_gia.universe, [3.5, 5.0, 5.0])

dung_gio['tre'] = fuzz.trimf(dung_gio.universe, [0, 0, 50])
dung_gio['dung_gio'] = fuzz.trimf(dung_gio.universe, [40, 60, 80])
dung_gio['som'] = fuzz.trimf(dung_gio.universe, [70, 100, 100])

he_so_gia['thap'] = fuzz.trimf(he_so_gia.universe, [1.0, 1.0, 1.3])
he_so_gia['trung_binh'] = fuzz.trimf(he_so_gia.universe, [1.2, 1.5, 1.8])
he_so_gia['cao'] = fuzz.trimf(he_so_gia.universe, [1.7, 2.1, 2.4])
he_so_gia['rat_cao'] = fuzz.trimf(he_so_gia.universe, [2.3, 3.0, 3.0])

diem_thuong['khong'] = fuzz.trimf(diem_thuong.universe, [0, 0, 20])
diem_thuong['it'] = fuzz.trimf(diem_thuong.universe, [10, 30, 50])
diem_thuong['trung_binh'] = fuzz.trimf(diem_thuong.universe, [40, 60, 80])
diem_thuong['cao'] = fuzz.trimf(diem_thuong.universe, [70, 100, 100])

# RULES (đã fix)
luat = [
    ctrl.Rule(khoang_cach['ngan'] & giao_thong['thap'] & nhu_cau['thap'], he_so_gia['thap']),

    ctrl.Rule(khoang_cach['ngan'] & giao_thong['trung_binh'] & nhu_cau['cao'], he_so_gia['trung_binh']),

    ctrl.Rule(khoang_cach['trung_binh'] & giao_thong['cao'] & nhu_cau['cao'], he_so_gia['cao']),

    ctrl.Rule(khoang_cach['dai'] & giao_thong['trung_binh'] & thoi_tiet['tot'], he_so_gia['trung_binh']),

    ctrl.Rule(khoang_cach['dai'] & giao_thong['cao'] & thoi_tiet['xau'], he_so_gia['rat_cao']),

    ctrl.Rule(khoang_cach['rat_xa'] & giao_thong['cao'] & nhu_cau['cao'], he_so_gia['rat_cao']),

    ctrl.Rule(khoang_cach['trung_binh'] & giao_thong['thap'] & nhu_cau['thap'], he_so_gia['trung_binh']),

    ctrl.Rule(khoang_cach['ngan'] & giao_thong['cao'] & thoi_tiet['xau'], he_so_gia['cao']),

    ctrl.Rule(khoang_cach['rat_xa'] & thoi_tiet['xau'], he_so_gia['rat_cao']),

    ctrl.Rule(khoang_cach['trung_binh'] & giao_thong['trung_binh'] & thoi_tiet['trung_binh'], he_so_gia['trung_binh']),


    # ================= 10 LUẬT ĐIỂM THƯỞNG =================
    ctrl.Rule(danh_gia['tot'] & dung_gio['som'], diem_thuong['cao']),

    ctrl.Rule(danh_gia['trung_binh'] & dung_gio['dung_gio'], diem_thuong['trung_binh']),

    ctrl.Rule(danh_gia['kem'] & dung_gio['tre'], diem_thuong['khong']),

    ctrl.Rule(khoang_cach['dai'] & giao_thong['cao'] & dung_gio['dung_gio'], diem_thuong['cao']),

    ctrl.Rule(khoang_cach['trung_binh'] & giao_thong['trung_binh'] & danh_gia['tot'], diem_thuong['trung_binh']),

    ctrl.Rule(danh_gia['kem'] & dung_gio['tre'], diem_thuong['khong']),

    ctrl.Rule(khoang_cach['rat_xa'] & thoi_tiet['xau'] & danh_gia['tot'], diem_thuong['cao']),

    ctrl.Rule(khoang_cach['ngan'] & danh_gia['trung_binh'] & dung_gio['dung_gio'], diem_thuong['it']),

    ctrl.Rule(khoang_cach['dai'] & giao_thong['cao'] & dung_gio['tre'], diem_thuong['it']),

    ctrl.Rule(khoang_cach['trung_binh'] & thoi_tiet['trung_binh'] & danh_gia['tot'], diem_thuong['trung_binh']),


    # ================= LUẬT PHỤ ĐỂ TRÁNH LỖI KHÔNG RA OUTPUT =================
    ctrl.Rule(giao_thong['trung_binh'] | nhu_cau['trung_binh'] | thoi_tiet['trung_binh'], he_so_gia['trung_binh']),
    ctrl.Rule(danh_gia['trung_binh'] | dung_gio['dung_gio'], diem_thuong['trung_binh'])
]

he_thong = ctrl.ControlSystem(luat)

# ===================== HÀM =====================
def tinh_khoang_cach(a, b):
    R = 6371
    lat1, lon1 = a
    lat2, lon2 = b
    dlat = radians(lat2-lat1)
    dlon = radians(lon2-lon1)
    x = sin(dlat/2)**2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)**2
    return 2*R*atan2(sqrt(x), sqrt(1-x)) * 1.3

def tinh_gia(don, den, gt, nc, tt, dg, dg2):
    sim = ctrl.ControlSystemSimulation(he_thong)

    kc = tinh_khoang_cach(dia_diem[don], dia_diem[den])

    sim.input['khoang_cach'] = min(kc, 50)
    sim.input['giao_thong'] = gt
    sim.input['nhu_cau'] = nc
    sim.input['thoi_tiet'] = tt
    sim.input['danh_gia'] = dg
    sim.input['dung_gio'] = dg2

    sim.compute()

    he_so = sim.output.get('he_so_gia', 1.5)
    thuong = sim.output.get('diem_thuong', 50)

    gia = (12000 + kc*4500) * he_so

    return kc, gia, he_so, thuong

# ===================== UI =====================
don = widgets.Dropdown(options=list(dia_diem.keys()), description="Đón:")
den = widgets.Dropdown(options=list(dia_diem.keys()), description="Đến:")

gt = widgets.IntSlider(value=50, min=0, max=100, description="Giao thông")
nc = widgets.IntSlider(value=50, min=0, max=100, description="Nhu cầu")
tt = widgets.IntSlider(value=30, min=0, max=100, description="Thời tiết")
dg = widgets.FloatSlider(value=4.5, min=1, max=5, step=0.1, description="Đánh giá")
dg2 = widgets.IntSlider(value=70, min=0, max=100, description="Đúng giờ")

btn = widgets.Button(description="Tính giá", button_style="success")
out = widgets.Output()

def phan_loai_gia(he_so):
    if he_so < 1.3:
        return "Thấp"
    elif he_so < 1.8:
        return "Trung bình"
    elif he_so < 2.4:
        return "Cao"
    else:
        return "Rất cao"

def phan_loai_thuong(diem):
    if diem < 20:
        return "Không có"
    elif diem < 50:
        return "Ít"
    elif diem < 80:
        return "Trung bình"
    else:
        return "Cao"

def ve_ban_do(diem_don, diem_den, ten_don, ten_den, gia, kc):
    lat_giua = (diem_don[0] + diem_den[0]) / 2
    lon_giua = (diem_don[1] + diem_den[1]) / 2

    ban_do = folium.Map(location=[lat_giua, lon_giua], zoom_start=13)

    folium.Marker(
        location=diem_don,
        popup=f"Điểm đón: {ten_don}",
        tooltip="Điểm đón",
        icon=folium.Icon(color="green")
    ).add_to(ban_do)

    folium.Marker(
        location=diem_den,
        popup=f"Điểm đến: {ten_den}",
        tooltip="Điểm đến",
        icon=folium.Icon(color="red")
    ).add_to(ban_do)

    folium.PolyLine(
        locations=[diem_don, diem_den],
        weight=5,
        opacity=0.8
    ).add_to(ban_do)

    folium.Marker(
        location=[lat_giua, lon_giua],
        popup=f"Khoảng cách ước tính: {kc:.2f} km<br>Giá: {gia:,.0f} VNĐ",
        tooltip="Thông tin chuyến đi",
        icon=folium.Icon(color="blue")
    ).add_to(ban_do)

    return ban_do

def click(b):
    with out:
        clear_output()

        if don.value == den.value:
            print("Điểm đón và điểm đến không được trùng nhau.")
            return

        kc, gia, hs, th = tinh_gia(
            don.value,
            den.value,
            gt.value,
            nc.value,
            tt.value,
            dg.value,
            dg2.value
        )

        muc_gia = phan_loai_gia(hs)
        muc_thuong = phan_loai_thuong(th)

        print("KẾT QUẢ HỆ THỐNG GIÁ GRABBIKE")
        print("--------------------------------")
        print("Điểm đón:", don.value)
        print("Điểm đến:", den.value)
        print("Khoảng cách ước tính:", round(kc, 2), "km")
        print("Giao thông:", gt.value, "/ 100")
        print("Nhu cầu:", nc.value, "/ 100")
        print("Thời tiết:", tt.value, "/ 100")
        print("Đánh giá khách hàng:", dg.value, "/ 5")
        print("Đúng giờ:", dg2.value, "/ 100")
        print("--------------------------------")
        print("Hệ số giá fuzzy:", round(hs, 2))
        print("Mức giá:", muc_gia)
        print("Giá cuối cùng:", f"{gia:,.0f} VNĐ")
        print("Điểm thưởng tài xế:", round(th, 1), "/ 100")
        print("Mức thưởng:", muc_thuong)
        print("--------------------------------")

        print("GIẢI THÍCH:")
        if gt.value >= 60:
            print("- Giao thông cao làm giá có xu hướng tăng.")
        if nc.value >= 60:
            print("- Nhu cầu đặt xe cao làm hệ thống tăng giá.")
        if tt.value >= 60:
            print("- Thời tiết xấu làm chuyến đi khó hơn nên giá có thể cao hơn.")
        if kc >= 15:
            print("- Khoảng cách rất xa nên giá và điểm thưởng có thể tăng.")
        if dg.value >= 3.5 and dg2.value >= 70:
            print("- Đánh giá tốt và đúng giờ/sớm nên tài xế nhận điểm thưởng cao hơn.")

        ban_do = ve_ban_do(
            diem_don=dia_diem[don.value],
            diem_den=dia_diem[den.value],
            ten_don=don.value,
            ten_den=den.value,
            gia=gia,
            kc=kc
        )

        display(ban_do)

btn.on_click(click)

display(don, den, gt, nc, tt, dg, dg2, btn, out)